openapi: 3.0.0
info:
  version: 1.0.0
  title: Health Tracker API
  description: This API provides endpoints for handling CRUD operations on the Health Tracker data.
  contact:
    name: Uchechukwu Henry Ezeigwe
    email: 20104352@mail.wit.ie
paths:
  /api/users:
    get:
      responses:
        200:
          description: This is a list of users in the app
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      description: Add a user to the app
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: The user has been created
                
  /api/users/{user-id}:
    get:
      parameters:
        - $ref: '#/components/parameters/UserIdPath'
      responses: 
        200: 
          description: This is a specific user in the app
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    patch:
      parameters:
        - $ref: '#/components/parameters/UserIdPath'
      responses:
        200:
          description: User has been successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      parameters:
        - $ref: '#/components/parameters/UserIdPath'
      responses:
        204:
          description: User deleted successfully
  /api/users/email/{email}:
    get:
      parameters:
        - $ref: '#/components/parameters/EmailIdPath'
      responses:
        200:
          description: This is a specific email of a user in the app
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /api/users/{user-id}/activities:
    get:
      parameters:
        - $ref: '#/components/parameters/UserIdPath'
      responses:
        200:
          description: This is a specific activity of a user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'
    delete:
      parameters:
        - $ref: '#/components/parameters/UserIdPath'
      responses:
        204:
          description: User activity has been successfully deleted
  /api/users/{user-id}/goals:
    get:
      parameters:
        - $ref: '#/components/parameters/FitnessGoalIdPath'
      responses:
        200:
          description: This is a specific fitness goal of a user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fitness-Goal'
    delete:
      parameters:
        - $ref: '#/components/parameters/FitnessGoalIdPath'
      responses:
        204:
          description: The fitness goal of a user has been successfully deleted
          
  /api/activities:
    get:
      responses:
        200:
          description: This is a list of activities in the app
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Activity'
    post:
      description: New activity added to the app
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Activity'
      responses:
        200:
          description: An activity has been added
          
  /api/activities/{activity-id}:
    get:
      parameters:
        - $ref: '#/components/parameters/ActivityIdPath'
      responses:
        200:
          description: This is a specific activity of a user in the app
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'
    patch:
      parameters:
        - $ref: '#/components/parameters/ActivityIdPath'
      responses:
        200:
          description: Activity has been successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'
    delete:
      parameters:
        - $ref: '#/components/parameters/ActivityIdPath'
      responses:
        204:
          description: User activity has been successfully deleted

  /api/goals:
    get:
      responses:
        200:
          description: This is a list of fitness goals in the app
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fitness-Goal'
    post:
      description: New fitness goal added to the app
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fitness-Goal'
      responses:
        200:
          description: A fitness goal has been added
  /api/goals/{goal-id}:
    get:
      parameters:
        - $ref: '#/components/parameters/FitnessGoalIdPath'
      responses:
        200:
          description: This is a specific fitness goal of a user in the app
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fitness-Goal'
    patch:
      parameters:
        - $ref: '#/components/parameters/FitnessGoalIdPath'
      responses:
        200:
          description: Fitness goal has been successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fitness-Goal'
    delete:
      parameters:
        - $ref: '#/components/parameters/FitnessGoalIdPath'
      responses:
        204:
          description: Fitness goal of a user has been successfully deleted

components:
  parameters:
    UserIdPath:
      name: user-id
      in: path
      description: user id path parameter
      required: true
      schema:
        type: integer
        example: 3232
    EmailIdPath:
      name: email
      in: path
      description: email id path parameter
      required: true
      schema:
        type: string
        example: henry@ezeigwe.com
    ActivityIdPath:
      name: activity-id
      in: path
      required: true
      schema:
        type: integer
        example: 3232
    FitnessGoalIdPath:
      name: goal-id
      description: fitness goal id path parameter
      in: path
      required: true
      schema:
        type: integer
        example: 123
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 3232
        name:
          type: string
          example: Henry Ezeigwe
        email:
          type: string
          example: henry@ezeigwe.com
    Activity:
      type: object
      properties:
        id:
          type: integer
          example: 3232
        duration:
          type: string
          example: learning
        description:
          type: string
          example: Various forms of skill development, studying, or exploring new subjects
        calories:
          type: integer
          example: 150
        started:
          type: string
          format: date-time
          example: "2023-11-05T10:00:00Z"
        userId:
          type: integer
          example: 789
    Fitness-Goal:
      type: object
      properties:
        id:
          type: integer
          example: 123
        goalType:
          type: string
          example: Weight Loss
        target:
          type: string
          example: 5 Days
        duration:
          type: string
          example: 3 Months
        initialUserStatus:
          type: string
          example: Fit
        startDate:
          type: string
          format: date-time
          example: "2023-11-05T08:00:00Z"
        endDate:
          type: string
          format: date-time
          example: "2023-12-05T08:00:00Z"
        userId:
          type: integer
          example: 456


